# oc create secret generic person-server \
#  --from-literal database_username=h2 \
#  --from-literal database_password=h2 \
#  --from-literal database_url='jdbc:h2:mem:default'
apiVersion: v1
data:
  database_username: aDI=
  database_password: aDI=
  database_url: amRiYzpoMjptZW06ZGVmYXVsdA==
kind: Secret
metadata:
  name: person-server
