quarkus:
  devservices:
    enabled: true
  datasource:
    devservices:
      enabled: true
      image-name: postgres:16.9
      username: postgres
      password: postgres
      db-name: db
      port: 5432
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/db
  hibernate-orm:
    schema-management:
      strategy: drop-and-create
    log:
      sql: true
