quarkus:
  log:
    console:
      json:
        enabled: false
  devservices:
    enabled: false
  datasource:
    db-kind: h2
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    jdbc:
      url: ${DB_URL}
  hibernate-orm:
    physical-naming-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl'
    schema-management:
      strategy: drop-and-create
