quarkus:
  # PostgreSQL
  # devservices:
  #   enabled: true
  # datasource:
  #   devservices:
  #     enabled: true
  #     image-name: postgres:16.9
  #     username: postgres
  #     password: postgres
  #     db-name: db
  #     port: 5432
  #   username: postgres
  #   password: postgres
  #   jdbc:
  #     url: jdbc:postgresql://localhost:5432/db

  # H2
  datasource:
    username: h2
    password: h2
    jdbc:
      url: jdbc:h2:mem:default
  hibernate-orm:
    schema-management:
      strategy: drop-and-create
    log:
      sql: true
